<?php

namespace Database\Factories;

use App\Models\Author;
use Closure;
use Illuminate\Database\Eloquent\Factories\Factory;

class AuthorFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            //
        ];
    }

    public function afterCreating(Closure $callback)
    {
        return parent::afterCreating($callback); // TODO: Change the autogenerated stub
    }

}
